compute rect sizes before drawing bodies
Adanos020/egui_dock pull request #134
Opened 2023-05-29 17:26 UTC by lvaroqui

2023-05-29 19:13 UTC, Adanos020 requested changes
Great job, this does indeed fix the crash!

2023-05-29 19:45 UTC, Adanos020 approved these changes

2023-05-29 19:45 UTC, merged

2023-05-29 21:31 UTC, lvaroqui commented
@Adanos020, should we release a patch version and yank 6.0.0?

2023-05-29 21:33 UTC, Adanos020 commented
I'll just release 0.6.1, there's no reason to yank 0.6.0

2023-05-29 21:39 UTC, lvaroqui commented
Sounds good :) I don't have much experience with crates deployment, was just wondering!

2023-05-29 22:10 UTC, Adanos020 commented
I'd say as long as a release doesn't introduce a security vulnerability, it's fine for it to stay :)

2023-05-29 22:12 UTC, lvaroqui commented
Should I back-port the fix to 0.5 for people still using egui 0.21?

2023-05-29 22:35 UTC, Adanos020 commented
The author of the issue mentioned that this bug didn't occur in 0.5, right?

2023-05-30 06:12 UTC, lvaroqui commented
We introduce the change in 0.5.1, so I think it's probably there as well, I'll have to check!

2023-05-30 08:15 UTC, Adanos020 commented
Ah okay, that makes sense. 0.5.2 could be our target version feel the patch, I hope.

2023-06-01 17:17 UTC, Adanos020 commented
@lvaroqui Sure, we can merge your changes here: https://github.com/Adanos020/egui_dock/tree/0.5.x-backports