one drag to resize them all
Adanos020/egui_dock pull request #155
Opened 2023-08-12 13:09 UTC by FreddyFunk

Currently only a draft for a discussion on discord.

2023-08-20 20:56 UTC, Adanos020 commented
Hey, can you write more about this here, so those that aren't on Discord can see what this is about?

2023-08-23 19:27 UTC, FreddyFunk commented
done :)

2023-08-25 10:25 UTC, Adanos020 requested changes
This is looking pretty good so far.

I wouldn't merge this PR just yet since it seems a bit incomplete without making the junctions snap together when they form an intersection. Once that's implemented, I'll happily accept it!

2023-08-25 10:25 UTC, Adanos020 commented on src/widgets/dock_area/mod.rs
> +        let mut separators: Vec<LineSeparator> = vec![];
The type annotation isn't necessary here.

2023-08-25 10:25 UTC, Adanos020 commented on src/widgets/dock_area/mod.rs
> +    fn show_cross_section_separators(&mut self, ui: &mut Ui, separators: Vec<LineSeparator>) {
I'd rename this to `show_separator_junctions`. We aren't really creating new separators here, just new interaction areas between existing ones. Also, a cross-section is the surface exposed when you slice through a solid object :)

2023-08-25 10:25 UTC, Adanos020 commented on src/widgets/dock_area/mod.rs
> +        let mut cross_section_seperators: Vec<CrossSeparator> = vec![];
Rename to `junctions`. Type annotation is unnecessary here too.

2023-08-25 10:25 UTC, Adanos020 commented on src/widgets/dock_area/mod.rs
> +            for sep2 in separators[i + 1..].iter() {
Shouldn't there be an `if i == separators.len() - 1 { break; }`? That `i + 1` worries me because it will go out of bounds on the final element.

2023-08-25 10:25 UTC, Adanos020 commented on src/widgets/dock_area/mod.rs
> +struct CrossSeparator {
Add an empty line above and rename to `SeparatorJunction`.

2023-08-25 10:25 UTC, Adanos020 commented on src/widgets/dock_area/mod.rs
> +#[derive(Copy, Clone)]
Add an empty line above.

2023-08-25 10:25 UTC, Adanos020 commented on src/widgets/dock_area/mod.rs
> +                        // overwise it may overlap on other separator / bodies when
*otherwise :)

2024-07-03 18:40 UTC, closed without merging