Added option to change tab bar height
Adanos020/egui_dock pull request #62
Opened 2022-11-03 02:52 UTC by Avarel

![image](https://user-images.githubusercontent.com/10081540/199639082-2f143bc0-9213-4956-a365-2d094669fd7b.png)

New option to change the tab bar's height. Using the default option (24.0) should yield no visual difference. The tab add button looks a little off with this change though, so that's up for further design/discussion I think.

2022-11-03 14:39 UTC, Adanos020 commented
Yeah, before we merge this, we need to address the add button. Perhaps make its size the same as the close button's?

2022-11-04 02:30 UTC, Avarel commented
Done, not a fan though because to make it the same size I basically have to query the font for a size (since the close button has the same size as the galley's height)

2022-11-06 13:45 UTC, Adanos020 requested changes
I noticed that the click area of the add button still resizes with the tab bar height: notice how the add button gets highlighted when you hover over the area around it with increased bar height. This needs to be fixed before merging.

2022-12-10 23:28 UTC, Avarel commented
Sorry took me a while to get to this, but the click area for the add button has been fixed.

2022-12-11 19:22 UTC, Adanos020 requested changes

2022-12-11 19:22 UTC, Adanos020 commented on CHANGELOG.md
> +- `Style` now includes an option to change the tab's height (url pending).
Add an `###Added` section above this point

2022-12-11 19:30 UTC, Adanos020 approved these changes

2022-12-11 19:35 UTC, merged