Added ability to remove tab (using logic from render)
Adanos020/egui_dock pull request #70
Opened 2022-11-19 06:37 UTC by awestlake87

I wanted to be able to add/remove tabs in different parts of the gui (i.e. in a View menu). The add is already supported with push_to_focused_leaf, but the remove was not available as an API call. I was able to find it in the render logic and put it in its own function and I thought this might be useful for other people.

toggled on:
![image](https://user-images.githubusercontent.com/12837524/202838007-f9e606a6-d2a2-4b35-863e-188b4439f255.png)

toggled off:
![image](https://user-images.githubusercontent.com/12837524/202838018-df621fd9-e8de-4993-b8b8-953df01b9714.png)

2022-11-21 10:40 UTC, Adanos020 requested changes
1. Add this to CHANGELOG.md
2. Include an example, can be a new app or an extra demo in examples/hello.rs

2022-11-25 01:40 UTC, awestlake87 commented
> 1. Add this to CHANGELOG.md
> 
>     2. Include an example, can be a new app or an extra demo in examples/hello.rs

Alright, I made the changes!

2022-11-28 01:39 UTC, awestlake87 commented on src/tree.rs
> +    pub fn remove_tab(&mut self, remove: (NodeIndex, TabIndex)) -> Option<Tab> {
Added docs, and fixed the clippy issues for CI

2022-11-28 08:10 UTC, Jerrody approved these changes

2022-11-28 10:41 UTC, Adanos020 approved these changes

2022-11-28 10:42 UTC, merged